#!/usr/bin/env php
<?php
/**
 * Mod command line script for Unix/Linux.
 *
 * This is the bootstrap script for running modc on Unix/Linux.
 *
 * @author Qiang Xue <qiang.xue@gmail.com>
 * @link http://www.modframework.com/
 * @copyright 2008 Mod Software LLC
 * @license http://www.modframework.com/license/
 */

require_once(dirname(__FILE__).'/modc.php');
